# Generated by Django 3.2.12 on 2022-03-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('modelo_equipo', models.CharField(max_length=40)),
                ('numero_telefono', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fichatecnica',
            fields=[
                ('numero_ficha', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_recibido', models.DateField()),
                ('problema_tecnico', models.CharField(max_length=300)),
                ('reparado', models.BooleanField()),
                ('fecha_entregado', models.DateField()),
            ],
        ),
    ]
