# Generated by Django 3.2.12 on 2022-04-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appagcelulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_nac', models.DateField()),
            ],
        ),
    ]
